# Project 2 - Ames Housing Data and Kaggle Challenge
## Revisited

When reviewing the various projects I completed during my time with General Assembly I found that Project 2, based on an existing Kaggle challenge, offered to most room for improvement. My notebooks were a mess: there was no clear organization to the repository as a whole and each individual notebook represented the full 'Data Science Process' (Cleaning through Model Deployment), each for a different list of features. 

While the project was not particularly complicated, the way in which I originally approached the project was: I now had a chance to improve upon the work I had done in a more succinct, cleaner manner. 

**Imports:**

In [30]:
import pandas as pd
pd.set_option("display.max_columns", None)

import numpy as np
np.random.seed(42)

import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style = "darkgrid")

from sklearn import metrics 
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression, LassoCV, RidgeCV
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, cross_val_predict

**Reading in Model-Ready Data**

In [2]:
#reading in training and testing data
ames_df = pd.read_csv('../datasets/train_clean.csv')
ames_test_df = pd.read_csv('../datasets/test_clean.csv')

In [3]:
ames_df.head()

ms_subclass ms_zoning  lot_frontage  lot_area street alley lot_shape  \
0           60        RL          68.0     13517   Pave   NaN       IR1   
1           60        RL          43.0     11492   Pave   NaN       IR1   
2           20        RL          68.0      7922   Pave   NaN       Reg   
3           60        RL          73.0      9802   Pave   NaN       Reg   
4           50        RL          82.0     14235   Pave   NaN       IR1   

  land_contour utilities lot_config land_slope neighborhood condition_1  \
0          Lvl    AllPub    CulDSac        Gtl       Sawyer        RRAe   
1          Lvl    AllPub    CulDSac        Gtl      SawyerW        Norm   
2          Lvl    AllPub     Inside        Gtl        NAmes        Norm   
3          Lvl    AllPub     Inside        Gtl       Timber        Norm   
4          Lvl    AllPub     Inside        Gtl      SawyerW        Norm   

  condition_2 bldg_type house_style  overall_qual  overall_cond  year_built  \
0        Norm      1Fam      2Story             6             8        1976   
1        Norm      1Fam      2Story             7             5        1996   
2        Norm      1Fam      1Story             5             7        1953   
3        Norm      1Fam      2Story             5             5        2006   
4        Norm      1Fam      1.5Fin             6             8        1900   

   year_remod/add roof_style roof_matl exterior_1st exterior_2nd mas_vnr_type  \
0            2005      Gable   CompShg      HdBoard      Plywood      BrkFace   
1            1997      Gable   CompShg      VinylSd      VinylSd      BrkFace   
2            2007      Gable   CompShg      VinylSd      VinylSd         None   
3            2007      Gable   CompShg      VinylSd      VinylSd         None   
4            1993      Gable   CompShg      Wd Sdng      Plywood         None   

   mas_vnr_area exter_qual exter_cond foundation bsmt_qual bsmt_cond  \
0         289.0         Gd         TA     CBlock        TA        TA   
1         132.0         Gd         TA      PConc        Gd        TA   
2           0.0         TA         Gd     CBlock        TA        TA   
3           0.0         TA         TA      PConc        Gd        TA   
4           0.0         TA         TA      PConc        Fa        Gd   

  bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1 bsmtfin_type_2  bsmtfin_sf_2  \
0            No            GLQ         533.0            Unf           0.0   
1            No            GLQ         637.0            Unf           0.0   
2            No            GLQ         731.0            Unf           0.0   
3            No            Unf           0.0            Unf           0.0   
4            No            Unf           0.0            Unf           0.0   

   bsmt_unf_sf  total_bsmt_sf heating heating_qc central_air electrical  \
0        192.0          725.0    GasA         Ex           Y      SBrkr   
1        276.0          913.0    GasA         Ex           Y      SBrkr   
2        326.0         1057.0    GasA         TA           Y      SBrkr   
3        384.0          384.0    GasA         Gd           Y      SBrkr   
4        676.0          676.0    GasA         TA           Y      SBrkr   

   1st_flr_sf  2nd_flr_sf  low_qual_fin_sf  gr_liv_area  bsmt_full_bath  \
0         725         754                0         1479             0.0   
1         913        1209                0         2122             1.0   
2        1057           0                0         1057             1.0   
3         744         700                0         1444             0.0   
4         831         614                0         1445             0.0   

   bsmt_half_bath  full_bath  half_bath  bedroom_abvgr  kitchen_abvgr  \
0             0.0          2          1              3              1   
1             0.0          2          1              4              1   
2             0.0          1          0              3              1   
3             0.0          2          1          

In [4]:
ames_test_df.head()

ms_subclass ms_zoning  lot_frontage  lot_area street alley lot_shape  \
0          190        RM          69.0      9142   Pave  Grvl       Reg   
1           90        RL          68.0      9662   Pave   NaN       IR1   
2           60        RL          58.0     17104   Pave   NaN       IR1   
3           30        RM          60.0      8520   Pave   NaN       Reg   
4           20        RL          68.0      9500   Pave   NaN       IR1   

  land_contour utilities lot_config land_slope neighborhood condition_1  \
0          Lvl    AllPub     Inside        Gtl      OldTown        Norm   
1          Lvl    AllPub     Inside        Gtl       Sawyer        Norm   
2          Lvl    AllPub     Inside        Gtl      Gilbert        Norm   
3          Lvl    AllPub     Inside        Gtl      OldTown        Norm   
4          Lvl    AllPub     Inside        Gtl        NAmes        Norm   

  condition_2 bldg_type house_style  overall_qual  overall_cond  year_built  \
0        Norm    2fmCon      2Story             6             8        1910   
1        Norm    Duplex      1Story             5             4        1977   
2        Norm      1Fam      2Story             7             5        2006   
3        Norm      1Fam      1Story             5             6        1923   
4        Norm      1Fam      1Story             6             5        1963   

   year_remod/add roof_style roof_matl exterior_1st exterior_2nd mas_vnr_type  \
0            1950      Gable   CompShg      AsbShng      AsbShng         None   
1            1977      Gable   CompShg      Plywood      Plywood         None   
2            2006      Gable   CompShg      VinylSd      VinylSd         None   
3            2006      Gable   CompShg      Wd Sdng      Wd Sdng         None   
4            1963      Gable   CompShg      Plywood      Plywood      BrkFace   

   mas_vnr_area exter_qual exter_cond foundation bsmt_qual bsmt_cond  \
0           0.0         TA         Fa      Stone        Fa        TA   
1           0.0         TA         TA     CBlock        Gd        TA   
2           0.0         Gd         TA      PConc        Gd        Gd   
3           0.0         Gd         TA     CBlock        TA        TA   
4         247.0         TA         TA     CBlock        Gd        TA   

  bsmt_exposure bsmtfin_type_1  bsmtfin_sf_1 bsmtfin_type_2  bsmtfin_sf_2  \
0            No            Unf             0            Unf             0   
1            No            Unf             0            Unf             0   
2            Av            GLQ           554            Unf             0   
3            No            Unf             0            Unf             0   
4            No            BLQ           609            Unf             0   

   bsmt_unf_sf  total_bsmt_sf heating heating_qc central_air electrical  \
0         1020           1020    GasA         Gd           N      FuseP   
1         1967           1967    GasA         TA           Y      SBrkr   
2          100            654    GasA         Ex           Y      SBrkr   
3          968            968    GasA         TA           Y      SBrkr   
4          785           1394    GasA         Gd           Y      SBrkr   

   1st_flr_sf  2nd_flr_sf  low_qual_fin_sf  gr_liv_area  bsmt_full_bath  \
0         908        1020                0         1928               0   
1        1967           0                0         1967               0   
2         664         832                0         1496               1   
3         968           0                0          968               0   
4        1394           0                0         1394               1   

   bsmt_half_bath  full_bath  half_bath  bedroom_abvgr  kitchen_abvgr  \
0               0          2          0              4              2   
1               0          2          0              6              2   
2               0          2          1              3              1   
3               0          1          0          

In [5]:
ames_df.shape

(2051, 79)

In [6]:
ames_test_df.shape

(878, 78)

**Setting Features**

In [7]:
ames_corr = ames_df.corr()['saleprice'][:-1]
list_feats = ames_corr[(ames_corr > 0.25)].sort_values(ascending = False).keys()
list_feats

Index(['overall_qual', 'gr_liv_area', 'garage_area', 'garage_cars',
       'total_bsmt_sf', '1st_flr_sf', 'year_built', 'year_remod/add',
       'full_bath', 'garage_yr_blt', 'totrms_abvgrd', 'mas_vnr_area',
       'fireplaces', 'bsmtfin_sf_1', 'open_porch_sf', 'wood_deck_sf',
       'lot_frontage', 'lot_area', 'bsmt_full_bath', 'half_bath'],
      dtype='object')

**Train-Test Split**

In [8]:
#setting features and target:
X = ames_df[list_feats]
y = ames_df[['saleprice']]

# Train/test split data
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size = 0.20,
                                                    random_state = 42)

In [9]:
X.head()

overall_qual  gr_liv_area  garage_area  garage_cars  total_bsmt_sf  \
0             6         1479        475.0          2.0          725.0   
1             7         2122        559.0          2.0          913.0   
2             5         1057        246.0          1.0         1057.0   
3             5         1444        400.0          2.0          384.0   
4             6         1445        484.0          2.0          676.0   

   1st_flr_sf  year_built  year_remod/add  full_bath  garage_yr_blt  \
0         725        1976            2005          2         1976.0   
1         913        1996            1997          2         1997.0   
2        1057        1953            2007          1         1953.0   
3         744        2006            2007          2         2007.0   
4         831        1900            1993          2         1957.0   

   totrms_abvgrd  mas_vnr_area  fireplaces  bsmtfin_sf_1  open_porch_sf  \
0              6         289.0           0         533.0             44   
1              8         132.0           1         637.0             74   
2              5           0.0           0         731.0             52   
3              7           0.0           0           0.0              0   
4              6           0.0           0           0.0             59   

   wood_deck_sf  lot_frontage  lot_area  bsmt_full_bath  half_bath  
0             0          68.0     13517             0.0          1  
1             0          43.0     11492             1.0          1  
2             0          68.0      7922             1.0          0  
3           100          73.0      9802             0.0          1  
4             0          82.0     14235             0.0          0

In [10]:
# Check train/test shape
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((1640, 20), (411, 20), (1640, 1), (411, 1))

## Modeling

**Linear Regression**

In [11]:
lr_1 = LinearRegression()

lr_1.fit(X_train, y_train)
print(f'{lr_1.score(X_train, y_train)}, {lr_1.score(X_test, y_test)}')
print(abs(lr_1.score(X_train, y_train) - lr_1.score(X_test, y_test)))

0.8035217902997219, 0.8542037354316081
0.050681945131886175


In [20]:
cross_val_score(lr_1, X_train, y_train, cv = 5), cross_val_score(lr_1, X_test, y_test, cv = 5)

(array([0.85040102, 0.79312742, 0.84536824, 0.76974   , 0.55591379]),
 array([0.86085886, 0.88614659, 0.88814039, 0.82501001, 0.84135121]))

In [22]:
cross_val_score(lr_1, X_train, y_train, cv = 5).mean(), cross_val_score(lr_1, X_test, y_test, cv = 5).mean()

(0.7629100944317463, 0.8603014120567016)

In [25]:
cross_val_score(lr_1, X, y, cv = 5)

array([0.81552011, 0.85044161, 0.70982379, 0.86413026, 0.75786356])

In [26]:
cross_val_score(lr_1, X, y, cv = 5).mean()

0.7995558655903834

**Scaling with Standard Scaler**

In [23]:
sc = StandardScaler()

X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [24]:
lr_1.fit(X_train_sc, y_train)
lr_1.score(X_train_sc, y_train), lr_1.score(X_test_sc, y_test)

(0.803521790299722, 0.854203735431607)

In [27]:
cross_val_score(lr_1, X_train_sc, y_train, cv = 5), cross_val_score(lr_1, X_test_sc, y_test, cv = 5)

(array([0.85040102, 0.79312742, 0.84536824, 0.76974   , 0.55591379]),
 array([0.86085886, 0.88614659, 0.88814039, 0.82501001, 0.84135121]))

In [28]:
cross_val_score(lr_1, X_train_sc, y_train, cv = 5).mean(), cross_val_score(lr_1, X_test_sc, y_test, cv = 5).mean()

(0.7629100944317464, 0.8603014120567014)

**LASSO**

In [35]:
y_train.shape

(1640, 1)

In [34]:
y_train['saleprice'].shape

(1640,)

In [36]:
#Lasso:
lasso = LassoCV()

lasso.fit(X_train_sc, y_train['saleprice'])
lasso.score(X_train_sc, y_train['saleprice']), lasso.score(X_test_sc, y_test['saleprice'])

(0.8024640546197501, 0.8548114245713652)